// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotDefteriAPI.Data;

namespace NotDefteriAPI.Data.Migrations
{
    [DbContext(typeof(NotDbContext))]
    partial class NotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NotDefteriAPI.Data.Not", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Notlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Baslik = "Alışveriş Listesi",
                            Icerik = "Şampuan, 1.5 Litre Su, Ekmek, 1 Kilo kiraz",
                            OlusturulmaTarihi = new DateTime(2022, 6, 11, 2, 14, 31, 182, DateTimeKind.Local).AddTicks(5392)
                        },
                        new
                        {
                            Id = 2,
                            Baslik = "İş Notlarım",
                            Icerik = "ASP.NET CORE WEB API ile Not Defteri uygulaması yapılacak",
                            OlusturulmaTarihi = new DateTime(2022, 6, 11, 2, 14, 31, 183, DateTimeKind.Local).AddTicks(3992)
                        },
                        new
                        {
                            Id = 3,
                            Baslik = "Güzel Sözler",
                            Icerik = "\"Dünden ders çıkar, bugünü yaşa, yarın için umut et\" Albert Einstein",
                            OlusturulmaTarihi = new DateTime(2022, 6, 11, 2, 14, 31, 183, DateTimeKind.Local).AddTicks(4009)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
